
-- inserciones
insert into doctors (first_name, last_name) values ('Merla', 'Havvock');
insert into doctors (first_name, last_name) values ('Lindsay', 'Tregunnah');
insert into doctors (first_name, last_name) values ('Andrus', 'Nannini');
insert into doctors (first_name, last_name) values ('Issi', 'Lippiello');
insert into doctors (first_name, last_name) values ('Nerty', 'Ree');
insert into doctors (first_name, last_name) values ('Nicol', 'Escudier');
insert into doctors (first_name, last_name) values ('Hal', 'Iacovino');
insert into doctors (first_name, last_name) values ('Charmine', 'Keilty');
insert into doctors (first_name, last_name) values ('Petrina', 'Boughtflower');
insert into doctors (first_name, last_name) values ('Coral', 'Massenhove');
insert into doctors (first_name, last_name) values ('Raphaela', 'Cottell');
insert into doctors (first_name, last_name) values ('Ondrea', 'Acum');
insert into doctors (first_name, last_name) values ('Leila', 'Adrain');
insert into doctors (first_name, last_name) values ('Judye', 'Capehorn');
insert into doctors (first_name, last_name) values ('Klement', 'Sleeny');
insert into doctors (first_name, last_name) values ('Klarika', 'Maudsley');
insert into doctors (first_name, last_name) values ('Trever', 'Antonescu');
insert into doctors (first_name, last_name) values ('Faydra', 'McLewd');
insert into doctors (first_name, last_name) values ('Onida', 'Giraudoux');
insert into doctors (first_name, last_name) values ('Corry', 'Gosselin');
insert into doctors (first_name, last_name) values ('Hyman', 'Coppin');
insert into doctors (first_name, last_name) values ('Robby', 'Tombleson');
insert into doctors (first_name, last_name) values ('Elaine', 'Dossetter');
insert into doctors (first_name, last_name) values ('Vladimir', 'Cerron');
insert into doctors (first_name, last_name) values ('Cesar', 'Hinostroza');

insert into diseases (name) values ('Bronquitis aguda'), ('Sinusitis'), ('Infección urinaria'), ('Asma'), ('Neumonia');

insert into users (username, password) values ('admin', '123456');

insert into specialities (name, doctor_id) values ('Cardiologia', 1);
insert into specialities (name, doctor_id) values ('Cardiologia', 2);
insert into specialities (name, doctor_id) values ('Cardiologia', 3);
insert into specialities (name, doctor_id) values ('Cardiologia', 4);
insert into specialities (name, doctor_id) values ('Cardiologia', 5);
insert into specialities (name, doctor_id) values ('Pediatria', 6);
insert into specialities (name, doctor_id) values ('Pediatria', 7);
insert into specialities (name, doctor_id) values ('Pediatria', 8);
insert into specialities (name, doctor_id) values ('Pediatria', 9);
insert into specialities (name, doctor_id) values ('Pediatria', 10);
insert into specialities (name, doctor_id) values ('Medicina interna', 11);
insert into specialities (name, doctor_id) values ('Medicina interna', 12);
insert into specialities (name, doctor_id) values ('Medicina interna', 13);
insert into specialities (name, doctor_id) values ('Medicina interna', 14);
insert into specialities (name, doctor_id) values ('Medicina interna', 15);
insert into specialities (name, doctor_id) values ('Dermatología', 16);
insert into specialities (name, doctor_id) values ('Dermatología', 17);
insert into specialities (name, doctor_id) values ('Dermatología', 18);
insert into specialities (name, doctor_id) values ('Dermatología', 19);
insert into specialities (name, doctor_id) values ('Dermatología', 20);

INSERT INTO beds (id, cod) VALUES ('1', '1');
INSERT INTO beds (id, cod) VALUES ('2', '2');	
INSERT INTO beds (id, cod) VALUES ('3', '3');
INSERT INTO beds (id, cod) VALUES ('4', '4');
INSERT INTO beds (id, cod) VALUES ('5', '5');
INSERT INTO beds (id, cod) VALUES ('6', '6');
INSERT INTO beds (id, cod) VALUES ('7', '7');
INSERT INTO beds (id, cod) VALUES ('8', '8');
INSERT INTO beds (id, cod) VALUES ('9', '9');
INSERT INTO beds (id, cod) VALUES ('10', '10');
INSERT INTO beds (id, cod) VALUES ('11', '11');
INSERT INTO beds (id, cod) VALUES ('12', '12');
INSERT INTO beds (id, cod) VALUES ('13', '13');
INSERT INTO beds (id, cod) VALUES ('14', '14');
INSERT INTO beds (id, cod) VALUES ('15', '15');
INSERT INTO beds (id, cod) VALUES ('16', '16');
INSERT INTO beds (id, cod) VALUES ('17', '17');
INSERT INTO beds (id, cod) VALUES ('18', '18');
INSERT INTO beds (id, cod) VALUES ('19', '19');
INSERT INTO beds (id, cod) VALUES ('20', '20');
INSERT INTO beds (id, cod) VALUES ('21', '21');
INSERT INTO beds (id, cod) VALUES ('22', '22');
INSERT INTO beds (id, cod) VALUES ('23', '23');
INSERT INTO beds (id, cod) VALUES ('24', '24');
INSERT INTO beds (id, cod) VALUES ('25', '25');
INSERT INTO beds (id, cod) VALUES ('26', '26');
INSERT INTO beds (id, cod) VALUES ('27', '27');
INSERT INTO beds (id, cod) VALUES ('28', '28');
INSERT INTO beds (id, cod) VALUES ('29', '29');
INSERT INTO beds (id, cod) VALUES ('30', '30');

INSERT INTO families (id, cod) VALUES ('22', 'Aarón');
INSERT INTO families (id, cod) VALUES ('23', 'Abdul');
INSERT INTO families (id, cod) VALUES ('24', 'Abel');
INSERT INTO families (id, cod) VALUES ('25', 'Abelardo');
INSERT INTO families (id, cod) VALUES ('26', 'Abraham');
INSERT INTO families (id, cod) VALUES ('27', 'Adam');
INSERT INTO families (id, cod) VALUES ('28', 'Adolfo');
INSERT INTO families (id, cod) VALUES ('29', 'Adrián');
INSERT INTO families (id, cod) VALUES ('30', 'Agustín');
INSERT INTO families (id, cod) VALUES ('31', 'Aladino');
INSERT INTO families (id, cod) VALUES ('32', 'Alan');
INSERT INTO families (id, cod) VALUES ('33', 'Alberto');
INSERT INTO families (id, cod) VALUES ('34', 'Alejandro');
INSERT INTO families (id, cod) VALUES ('35', 'Alessandro');
INSERT INTO families (id, cod) VALUES ('36', 'Alexis');
INSERT INTO families (id, cod) VALUES ('37', 'Alfonso');
INSERT INTO families (id, cod) VALUES ('38', 'Bartolomé');
INSERT INTO families (id, cod) VALUES ('39', 'Belisario');
INSERT INTO families (id, cod) VALUES ('40', 'Benjamín');
INSERT INTO families (id, cod) VALUES ('41', 'Benedicto');
INSERT INTO families (id, cod) VALUES ('42', 'Brian');
INSERT INTO families (id, cod) VALUES ('43', 'Casimiro');
INSERT INTO families (id, cod) VALUES ('44', 'César');
INSERT INTO families (id, cod) VALUES ('45', 'Christian');
INSERT INTO families (id, cod) VALUES ('46', 'Claudio');
INSERT INTO families (id, cod) VALUES ('47', 'Constantino');
INSERT INTO families (id, cod) VALUES ('48', 'Cristóbal');
INSERT INTO families (id, cod) VALUES ('49', 'Domingo');
INSERT INTO families (id, cod) VALUES ('50', 'Eduardo');
INSERT INTO families (id, cod) VALUES ('51', 'Elías');
